name: Deploy to Amazon S3

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
        default: 'dev'
      ARTIFACT_NAME:
        required: true
        type: string
        default: 'generated-artifacts'
      APPROVERS:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      AWS_S3_BUCKET_ANGULAR:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: Generate token
    #   id: generate_token
    #   uses: tibdex/github-app-token@v1
    #   with:
    #     app_id: ${{ secrets.APP_ID }}
        
    #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: trstringer/manual-approval@v1.9.0
      with:
        secret: ${{ github.TOKEN }}
        approvers:
        minimum-approvals: 1
        exclude-workflow-initiator-as-approver: false
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: generated
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
    - name: Deploy to S3
      run: ./.github/scripts/deploy.sh
      shell: bash
      env:
        ORIGIN_PATH: 'generated/dist'
        BUCKET: ${{ secrets.AWS_S3_BUCKET_ANGULAR }}-${{ inputs.CI_ENV}}
  
        #run: aws s3 sync generated/dist 's3://${{ secrets.AWS_S3_BUCKET_ANGULAR }}-${{ env.dev}}' --cache-control no-cache,no-store,must-revalidate --delete
    #- name: Deploy to production
    #  run: echo deploying
       