# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI with pnpm

on:
  push:
    branches: [ "feature/implementCICD-gitHubAction-40" ]
  pull_request:
    branches: [ "feature/implementCICD-gitHubAction-40" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: SetupNode
      uses: actions/setup-node@v3
      with:
        # Version Spec of the version to use in SemVer notation.
        # It also emits such aliases as lts, latest, nightly and canary builds
        # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        node-version: '16.x'
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, gulp, prettier, typescript]
    - name: Build client
      run: pnpm build
